### ISSUE TITLE
Uncaught TypeError: Cannot read property 'oneOf' of undefined

### ISSUE THREAD

**Issue by logancalldev** [moarwick/react-mt-svg-lines#12]
Call Stack:
```
index.js:415 Uncaught TypeError: Cannot read property 'oneOf' of undefined
    at Object.169../utils.js (index.js:415)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.600.prop-types (Form.js:7)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.601.../reducers (FormContainer.js:5)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.598../ErrorBoundary (App.js:2)
```
The line it's referring to:
```
timing: _react2.default.PropTypes.oneOf([// easing type
  'ease', 'ease-in', 'ease-out', 'ease-in-out', 'linear', 'step-start', 'step-end']),
```

Conflict with React 16? Something else?

**Comment by AlithAnar** [comment]
If you are using react 16 - https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by moarwick** [comment]
Thanks. I already updated to the separate `prop-types` package, but looks like I missed one location. Problem is `React.PropTypes` here https://github.com/moarwick/react-mt-svg-lines/blob/master/src/index.js#L27

Will fix soon..

**Comment by moarwick** [comment]
Fixed in 0.8.2

**Comment by logancalldev** [comment]
Thanks @moarwick. Looks like there's a stray console.log in the release. :)

**Comment by moarwick** [comment]
grrr.. try 0.8.3 :)
