### ISSUE TITLE
Randomized className attribute causes react-test-renderer snapshots to fail

### ISSUE THREAD

**Issue by MikeLuDev** [moarwick/react-mt-svg-lines#19]
**Issue**

When using `jest` and `react-test-renderer` to snapshot test components containing `MtSvgLines`, the snapshot test will always fail because a new random `className` is generated, regardless of if a `className` is specified explicitly.

**Example of failing test** 

![failshot](https://user-images.githubusercontent.com/25614124/43994565-48f7d75e-9d5c-11e8-8cef-25664811fd85.png)

**Proposed solution**

Either add a method to disable random `className` generation, or add support for snapshot testing using `jest` and `react-test-renderer`.

**Comment by moarwick** [comment]
hey @MikeLuDev, the latest 0.9.0 should fix the issue. classNames should now be predictable. see https://github.com/moarwick/react-mt-svg-lines/releases/tag/v0.9.0
