### ISSUE TITLE
Can't resolve 'react-mt-svg-lines' in '/opt/build/repo/src/components'

### ISSUE THREAD

**Issue by jT2a** [moarwick/react-mt-svg-lines#23]
Hi, I am trying to deploy to netlify & vercel but building creates this error. 

I have tried to build in gatsby locally and it works fine. Just when push to deploy doesn't compile.

Thanks for the great package.

**Comment by moarwick** [comment]
hi @desmondshowell, thanks for using the lib. i haven't updated it in some time. do you mind posting the error you are getting?

**Comment by jT2a** [comment]
Hi @moarwick, 

"Can't resolve 'react-mt-svg-lines' in '/opt/build/repo/src/components'" This is the error that comes from the Netlify console. It only happens when I build on the production server. 

I am using GatsbyJS and it compiles fine locally.

**Comment by moarwick** [comment]
strange, i think something related to Gatsby/Netlify. it appears to be a pretty common issue with other packages, if you [search about](https://www.google.com/search?q=Netlify+can%27t+resolve+in+%27%2Fopt%2Fbuild%2Frepo%2Fsrc%2Fcomponents&rlz=1C5CHFA_enUS973US973&oq=Netlify+can%27t+resolve++in+%27%2Fopt%2Fbuild%2Frepo%2Fsrc%2Fcomponents&aqs=chrome..69i57j69i64.10603j0j7&sourceid=chrome&ie=UTF-8). maybe try adding the `"@tweenjs/tween.js": "16.7.0"` dependency to your `package.json` manually?
