### ISSUE TITLE
having issues with paths exported from illustrator

### ISSUE THREAD

**Issue by faceyspacey** [moarwick/react-mt-svg-lines#3]
I can't get paths exported from illustrator to work. It exports svgs like this one:

```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38.93 40.02"><title>vector-logo</title>

<path d="M382.79,279.74l-29,18a1.48,1.48,0,0,1-2.27-.95V282.1l8.7,6h0a1.12,1.12,0,0,0,.75.29,1.14,1.14,0,0,0,1.14-1.14,1.12,1.12,0,0,0-.05-0.33h0a1.11,1.11,0,0,0-.12-0.27L358,277.78l11.74-9.61,13,8.08a2,2,0,0,1,0,3.49h0Z" transform="translate(-344.88 -257.98)"/>

<path d="M351.77,264.22a0.68,0.68,0,0,0-.22-0.39V259.2c0-1.7,1.93-1.2,2.27-.95l13.2,8.2-12.95,3.84-2.29-6.07h0Z" transform="translate(-344.88 -257.98)"/>

<path d="M359.35,270.74a0.27,0.27,0,0,1,.14,0,0.29,0.29,0,0,1,.29.28,0.28,0.28,0,0,1-.12.23h0l-6.41,5.21,1.8,4a0.55,0.55,0,0,1,.06.12h0a0.5,0.5,0,0,1,0,.15,0.52,0.52,0,0,1-.86.39h0l-4.19-2.86L346.92,280h0a0.54,0.54,0,0,1-.2,0,0.51,0.51,0,0,1-.53-0.51,0.55,0.55,0,0,1,0-.18h0c0.44-1.18,1-2.74,1-2.78l-2.14-1.09a0.3,0.3,0,0,1-.22-0.29,0.33,0.33,0,0,1,.26-0.31h0l3.38-1.18,1.25-3.4a0.34,0.34,0,0,1,.3-0.23,0.31,0.31,0,0,1,.31.22l1.06,2.79,7.89-2.32,0,0h0Z" transform="translate(-344.88 -257.98)"/>

</svg>
```

And if I take the simplest path in there:

```
M351.77,264.22a0.68,0.68,0,0,0-.22-0.39V259.2c0-1.7,1.93-1.2,2.27-.95l13.2,8.2-12.95,3.84-2.29-6.07h0Z
```

it doesn't render. What's the difference between these style paths exported from Illustrator and what can I do to make them compatible?

**Comment by moarwick** [comment]
Had a quick look. It actually rendered fine for me, but I noticed the `transforms` in your svg. Basically your paths were defined way outside of your `viewBox`, and then moved in. 

Issues like these often happen when opening SVGs from other sources in Illustrator. Best way I know to clean it up, is to create a new Artboard and paste your shapes into it. Essentially, Illustrator's Artboard canvas is the `viewBox`, so you can set it to whatever size you want, then scale your drawing to fill it. But sometimes, even that doesn't seem work. As the final step, I often use `svgo` to process SVGs exported from Illustrator (with the `--disable=mergePaths` flag), with some additional hand-editing.

Also, to see your paths, you will need `stroke`, `strokeWidth` (or `stroke-width` depending on your ver. of React), and `fill` (if all the same, you can apply them wholesale to all paths at a `<g>` (group) level).

Try the version below. Hope it helps.. 

```
            <svg viewBox="0 0 96 102">
              <g fill="#999" stroke="#000" strokeWidth="1">
                <path d="M92.53 55.34l-69.92 45.05a3.5 3.5 0 0 1-4.87-.92l-.08-.12a3.78 3.78 0 0 1-.52-1.34V61.26l21 15a3.08 3.08 0 0 0 1.91.72 2.65 2.65 0 0 0 2.66-2.65v-.21a7.51 7.51 0 0 0-.41-1.5l-9.5-22.17 28.34-24.06 31.39 20.22a5.1 5.1 0 0 1 1.85 6.81 5 5 0 0 1-1.85 1.92z"/>
                <path d="M17.23 15.61V4c0-4.25 4.66-3 5.48-2.38l31.88 20.54-31.27 9.61s-4.92-13.3-6.09-16.16z"/>
                <path d="M36.56 32.77a.88.88 0 0 1 .54.84.7.7 0 0 1-.3.58l-15.47 13 4.34 10a1.4 1.4 0 0 1 .15.3 1.3 1.3 0 0 1 0 .38 1.27 1.27 0 0 1-2.08 1l-10.11-7.16L6 56.06a1.26 1.26 0 0 1-.48 0 1.27 1.27 0 0 1-1.23-1.26 1.43 1.43 0 0 1 0-.45c1.06-3 2.41-6.86 2.41-6.94l-5.17-2.76a.74.74 0 0 1-.53-.72.82.82 0 0 1 .62-.77l8.16-3 3-8.5a.82.82 0 0 1 .72-.57.75.75 0 0 1 .75.55l2.56 6.94 19-5.81a1.15 1.15 0 0 1 .75 0z"/>
              </g>
            </svg>
```

**Comment by faceyspacey** [comment]
Wow, thanks so much. It works perfectly. I'm going to fiddle with the artboards and try to do the same for my other paths.
