### ISSUE TITLE
End of Animation callback

### ISSUE THREAD

**Issue by zyzo** [moarwick/react-mt-svg-lines#4]
Hi,

Is there a way to provide a callback function that is called after the end of the animation ?

For e.g. something like this:
```javascript
<MtSvgLines callback={() => console.log('done')} ...otherProps />
```

**Comment by moarwick** [comment]
Should be easy, will look into it. Been working on a version with a JS tweener fallback for IE in between things. Should be soon, will add it then.

**Comment by moarwick** [comment]
The JS fallback update is more tricky than I thought (and I'm not finding much free time lately), so just pushed a minor update which add the `callback` prop. Let me know if you encounter any issues.
