### ISSUE TITLE
Compatibility IE 10, 11 Edge !

### ISSUE THREAD

**Issue by Oguima** [moarwick/react-mt-svg-lines#5]
Any possibility of compatibility with IE ?

**Comment by moarwick** [comment]
I tried putting in a JS fallback using Tween.js but could not get it to work reliably; feel free to check out the `feature/js-anim-apply` branch.. I may return to it but it felt like an uphill battle :(

**Comment by moarwick** [comment]
If still interested, please try latest version `0.6.0` -- it's not perfect, but at least something.

**Comment by Oguima** [comment]
IE 11 and Edge Works ... it´s not perfect, but excelent results, thanks.
