### ISSUE TITLE
Fix crash during Server Side Rendering

### ISSUE THREAD

**Issue by pocketjoso** [moarwick/react-mt-svg-lines#8]
Hi,
First of all thanks for your Component, it's awesome! 🎉 

The generated dist file has an unguarded `"performance"in window` check, which crashes when `window` is not defined during Server Side Rendering. I just had a quick look for where this code came from, and strangely enough it disappears (and fixes my issue) if I set `minimize:
 false` in the [webpack.dist.js config](https://github.com/moarwick/react-mt-svg-lines/blob/master/webpack.dist.js#L26)

For a React module I would really remove the (webpack) optimization all together, it not only causes this issue, but also makes debugging unnecessarily hard. The optimization will be handled by your end users in their own build process anyway.

A more typical export for a library like this would be a transpiled (not minimized or otherwise optimized) `lib` folder, mirroring your `src`, which you can get by just simply running `babel -d lib src`.

**Comment by moarwick** [comment]
@pocketjoso thanks for the feedback. i've been meaning to give this repo a little refresh, so appreciate the "kick in the butt" :) valid points, i didn't know too much about universal react when i wrote the plugin. quickly tried `babel -d dist src` but got some errors; worst case, i can just disable minification. i'm doing the fixes in the `update` branch if you wanted to have a look. still want to update some packages, maybe webpack 2.0..

**Comment by pocketjoso** [comment]
No problem. Let me know if I can help regarding the babel errors. `babel` needs to be installed, and on your path (which npm handles for you if you run it as a npm run task). The `lib` folder might need to exist. (btw the command was `babel -d lib src` (not `dist` - dist is indeed generally for a minified and dependency free single bundle file).

**Comment by moarwick** [comment]
just published 0.7.0. please give it a try if you get a chance.

**Comment by moarwick** [comment]
k, so 0.7.3 should work well enough server-side. i tested it in a Next.js app. however, since this library relies on generated unique (random) `classNames`, you will see `Warning: React attempted to reuse markup in a container but the checksum was invalid.` in the console. not really sure how to get around it easily :(

**Comment by pocketjoso** [comment]
The only way to get around that warning would be to somehow delay the actual animation from happening in the client, so that the first render on the client yields the same result as on the server, however this would delay the animation, so I'm not sure it's worth it.

Thanks for fixing the issue!
